# Generated by Django 5.2.7 on 2025-11-06 05:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reservas', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('creditos', models.IntegerField()),
                ('porcentajeEC1', models.IntegerField()),
                ('porcentajeEP1', models.IntegerField()),
                ('porcentajeEC2', models.IntegerField()),
                ('porcentajeEP2', models.IntegerField()),
                ('porcentajeEC3', models.IntegerField()),
                ('porcentajeEP3', models.IntegerField()),
                ('silabo_url', models.CharField(blank=True, max_length=512, null=True)),
                ('Fase1notaAlta_url', models.CharField(blank=True, max_length=512, null=True)),
                ('Fase1notaMedia_url', models.CharField(blank=True, max_length=512, null=True)),
                ('Fase1notaBaja_url', models.CharField(blank=True, max_length=512, null=True)),
                ('Fase2notaAlta_url', models.CharField(blank=True, max_length=512, null=True)),
                ('Fase2notaMedia_url', models.CharField(blank=True, max_length=512, null=True)),
                ('Fase2notaBaja_url', models.CharField(blank=True, max_length=512, null=True)),
                ('Fase3notaAlta_url', models.CharField(blank=True, max_length=512, null=True)),
                ('Fase3notaMedia_url', models.CharField(blank=True, max_length=512, null=True)),
                ('Fase3notaBaja_url', models.CharField(blank=True, max_length=512, null=True)),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
                'db_table': 'cursos_curso',
            },
        ),
        migrations.CreateModel(
            name='GrupoCurso',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('grupo', models.CharField(max_length=1)),
                ('capacidad', models.IntegerField()),
                ('curso', models.ForeignKey(db_column='curso_id', on_delete=django.db.models.deletion.RESTRICT, to='cursos.curso')),
                ('profesor', models.ForeignKey(blank=True, db_column='profesor_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.profesor')),
            ],
            options={
                'verbose_name': 'Grupo de Curso',
                'verbose_name_plural': 'Grupos de Cursos',
                'db_table': 'cursos_grupo_curso',
                'unique_together': {('curso', 'grupo')},
            },
        ),
        migrations.CreateModel(
            name='GrupoLaboratorio',
            fields=[
                ('grupo_curso', models.OneToOneField(db_column='id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='cursos.grupocurso')),
            ],
            options={
                'verbose_name': 'Grupo de Laboratorio',
                'verbose_name_plural': 'Grupos de Laboratorio',
                'db_table': 'cursos_grupo_laboratorio',
            },
        ),
        migrations.CreateModel(
            name='GrupoTeoria',
            fields=[
                ('grupo_curso', models.OneToOneField(db_column='id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='cursos.grupocurso')),
            ],
            options={
                'verbose_name': 'Grupo de Teoría',
                'verbose_name_plural': 'Grupos de Teoría',
                'db_table': 'cursos_grupo_teoria',
            },
        ),
        migrations.CreateModel(
            name='BloqueHorario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horaInicio', models.TimeField()),
                ('horaFin', models.TimeField()),
                ('dia', models.CharField(choices=[('LUNES', 'Lunes'), ('MARTES', 'Martes'), ('MIERCOLES', 'Miércoles'), ('JUEVES', 'Jueves'), ('VIERNES', 'Viernes')], max_length=10)),
                ('aula', models.ForeignKey(db_column='aula_id', on_delete=django.db.models.deletion.CASCADE, to='reservas.aula')),
                ('grupo_curso', models.ForeignKey(db_column='grupo_curso_id', on_delete=django.db.models.deletion.CASCADE, to='cursos.grupocurso')),
            ],
            options={
                'verbose_name': 'Bloque de Horario',
                'verbose_name_plural': 'Bloques de Horario',
                'db_table': 'cursos_bloque_horario',
            },
        ),
        migrations.CreateModel(
            name='TemaCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('orden', models.IntegerField()),
                ('completado', models.BooleanField()),
                ('fecha', models.DateField()),
                ('grupo_teoria', models.ForeignKey(db_column='grupo_teoria_id', on_delete=django.db.models.deletion.CASCADE, to='cursos.grupoteoria')),
            ],
            options={
                'verbose_name': 'Tema de Curso',
                'verbose_name_plural': 'Temas de Curso',
                'db_table': 'cursos_tema_curso',
            },
        ),
    ]
