# Generated by Django 5.2.7 on 2025-11-06 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='grupocurso',
            unique_together=set(),
        ),
    ]
