# Generated by Django 5.2.7 on 2025-11-06 05:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('estadoCuenta', models.BooleanField(default=True)),
                ('rol', models.CharField(choices=[('ADMIN', 'Administrador'), ('SECRETARIA', 'Secretaria'), ('PROFESOR', 'Profesor'), ('ESTUDIANTE', 'Estudiante')], max_length=10)),
            ],
            options={
                'verbose_name': 'Perfil Usuario',
                'verbose_name_plural': 'Perfiles Usuarios',
                'db_table': 'usuarios_perfil',
            },
        ),
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('perfil', models.OneToOneField(db_column='perfil_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='administrador', serialize=False, to='usuarios.perfil')),
            ],
            options={
                'verbose_name': 'Administrador',
                'verbose_name_plural': 'Administradores',
                'db_table': 'usuarios_administrador',
            },
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('perfil', models.OneToOneField(db_column='perfil_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='estudiante', serialize=False, to='usuarios.perfil')),
            ],
            options={
                'verbose_name': 'Estudiante',
                'verbose_name_plural': 'Estudiantes',
                'db_table': 'usuarios_estudiante',
            },
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('perfil', models.OneToOneField(db_column='perfil_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profesor', serialize=False, to='usuarios.perfil')),
                ('es_teoria', models.BooleanField(default=False)),
                ('es_lab', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Profesor',
                'verbose_name_plural': 'Profesores',
                'db_table': 'usuarios_profesor',
            },
        ),
        migrations.CreateModel(
            name='Secretaria',
            fields=[
                ('perfil', models.OneToOneField(db_column='perfil_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='secretaria', serialize=False, to='usuarios.perfil')),
            ],
            options={
                'verbose_name': 'Secretaria',
                'verbose_name_plural': 'Secretarias',
                'db_table': 'usuarios_secretaria',
            },
        ),
    ]
