# Generated by Django 5.2.7 on 2025-11-06 05:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cursos', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField()),
                ('EC1', models.FloatField(blank=True, null=True)),
                ('EP1', models.FloatField(blank=True, null=True)),
                ('EC2', models.FloatField(blank=True, null=True)),
                ('EP2', models.FloatField(blank=True, null=True)),
                ('EC3', models.FloatField(blank=True, null=True)),
                ('EP3', models.FloatField(blank=True, null=True)),
                ('estudiante', models.ForeignKey(db_column='estudiante_id', on_delete=django.db.models.deletion.CASCADE, to='usuarios.estudiante')),
                ('grupo_curso', models.ForeignKey(db_column='grupo_curso_id', on_delete=django.db.models.deletion.CASCADE, to='cursos.grupocurso')),
            ],
            options={
                'verbose_name': 'Matricula',
                'verbose_name_plural': 'Matriculas',
                'db_table': 'matricula_matricula',
                'unique_together': {('estudiante', 'grupo_curso')},
            },
        ),
        migrations.CreateModel(
            name='MatriculaLaboratorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estudiante', models.ForeignKey(db_column='estudiante_id', on_delete=django.db.models.deletion.CASCADE, to='usuarios.estudiante')),
                ('laboratorio', models.ForeignKey(db_column='laboratorio_id', on_delete=django.db.models.deletion.CASCADE, to='cursos.grupolaboratorio')),
            ],
            options={
                'verbose_name': 'Matrícula de Laboratorio',
                'verbose_name_plural': 'Matrículas de Laboratorio',
                'db_table': 'matricula_laboratorio',
                'unique_together': {('estudiante', 'laboratorio')},
            },
        ),
    ]
