# Generated by Django 5.2.7 on 2025-11-06 05:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('AULA_NORMAL', 'Aula Normal'), ('LABORATORIO', 'Laboratorio')], max_length=15)),
            ],
            options={
                'verbose_name': 'Aula',
                'verbose_name_plural': 'Aulas',
                'db_table': 'reservas_aula',
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_reserva', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('aula', models.ForeignKey(db_column='aula_id', on_delete=django.db.models.deletion.CASCADE, to='reservas.aula')),
                ('profesor', models.ForeignKey(db_column='profesor_id', on_delete=django.db.models.deletion.CASCADE, to='usuarios.profesor')),
            ],
            options={
                'verbose_name': 'Reserva de Aula',
                'verbose_name_plural': 'Reservas de Aulas',
                'db_table': 'reservas_reservas',
            },
        ),
    ]
