# Generated by Django 5.2.7 on 2025-11-06 05:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cursos', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroAsistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ipProfesor', models.CharField(max_length=255)),
                ('fechaClase', models.DateField()),
                ('horaInicioVentana', models.TimeField()),
                ('grupo_curso', models.ForeignKey(db_column='grupo_curso_id', on_delete=django.db.models.deletion.CASCADE, to='cursos.grupocurso')),
            ],
            options={
                'verbose_name': 'Registro de Asistencia',
                'verbose_name_plural': 'Registros de Asistencia',
                'db_table': 'RegistroAsistencia',
            },
        ),
        migrations.CreateModel(
            name='RegistroAsistenciaDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('PRESENTE', 'Presente'), ('FALTA', 'Falta')], max_length=10)),
                ('estudiante', models.ForeignKey(db_column='id_Estudiante', on_delete=django.db.models.deletion.CASCADE, to='usuarios.estudiante')),
                ('registro_asistencia', models.ForeignKey(db_column='id_RegistroAsistencia', on_delete=django.db.models.deletion.RESTRICT, to='asistencias.registroasistencia')),
            ],
            options={
                'verbose_name': 'Detalle de Asistencia',
                'verbose_name_plural': 'Detalles de Asistencia',
                'db_table': 'RegistroAsistencia_Detalle',
            },
        ),
    ]
